### ISSUE TITLE
🐛 Bug: Rows Inserted via REST API Not Visible in Kanban View

### ISSUE THREAD

**Issue by lmalma** [nocodb/nocodb#10057]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

When adding rows to a NocoDB table using the REST API, the rows successfully appear in the main table view but do not appear in the Kanban view. This issue persists even when there are no filters, sorting, or conditions applied to the Kanban view. Notably, the rows **do appear in Calendar, Grid, and Gallery views**, but they do not appear in the Kanban view. Refreshing the view, restarting the server, and clearing browser cache did not resolve the issue.

**Steps to Reproduce:**
1. Create a new table in NocoDB (version 0.258.7) with multiple columns.
2. Add a new row to the table using the REST API (POST request to `/api/v2/tables/.../records`).
3. Verify that the new row is visible in the main table view.
4. Switch to the Kanban view for the same table.

**Desired Behavior:**
The newly inserted row should be visible in the Kanban view, just as it appears in the main table view, Calendar, Grid, and Gallery views.

**Actual Behavior:**
The row is visible in the main table, Calendar, Grid, and Gallery views but does not appear in the Kanban view. This occurs even if there are no active filters, sorting rules, or specific conditions applied to the Kanban view.

**Environment Details:**
- **NocoDB Version:** 0.258.7
- **Server Environment:** Docker
- **Browser:** ‏Chrome version 131.0.6778.140

**Troubleshooting Steps Taken:**
- Verified that the API call was successful (HTTP 200) and that the row appears in the main table view.
- Checked for any filters, sorts, or conditions in the Kanban view (none were present).
- Refreshed the page and cleared browser cache.
- Restarted the NocoDB server.

**Possible Cause (Hypothesis):**
It is possible that the Kanban view does not automatically sync or reload rows inserted via the REST API. There may be a caching issue or a problem with the logic that fetches data for Kanban views.

**Additional Context:**
If there are any logs or debugging steps that could help identify the issue, I am happy to provide them. Please advise on any additional information you might need.

**Request for Assistance:**
- Are there any known issues or limitations related to API-inserted rows and Kanban views?
- Is there a recommended way to trigger a refresh or force an update to the Kanban view?

Thank you for your support.

### Desired Behavior

The newly inserted row should be visible in the Kanban view, just as it appears in the main table view, Calendar, Grid, and Gallery views.

### Project Details

```
NocoDB used as docker : true
NocoDB version :  0.258.7
Database used in NC_DB URL  : pg
Project was created  by clicking : New Project
Database on which spreadsheet is created : pg
OS on which NocoDB is running : linux ubuntu
Node.js version if running as node : v22.11.0
Database version : psql (PostgreSQL) 16.6 (Debian 16.6-1.pgdg120+1)
```

**Comment by DarkPhoenix2704** [comment]
Fixed in https://github.com/nocodb/nocodb/pull/10060

**Comment by lmalma** [comment]
Hello,  

Thank you for looking into this issue earlier. Unfortunately, I am still experiencing the problem where new records added via the API do not appear in the Kanban view.  

**Environment Details:**  
- Database: PostgreSQL  
- Version: 0.260.0
**Description of the Issue:**  
Even after ensuring that the API successfully inserts records into the database, these records do not show up in the Kanban view. I have tried refreshing the page and clearing the cache, but the issue persists.  

It seems like the Kanban view is not updating dynamically or fetching the latest data from the database after API interactions. Could you please confirm if there is a workaround or additional configuration required? Alternatively, is this a known limitation or bug for PostgreSQL setups?  

Thank you for your help and support.

**Comment by DarkPhoenix2704** [comment]
Hi @lmalma 

Would you be able to share the api request

**Comment by lmalma** [comment]
I would like to provide some additional details regarding the issue:

- When using an SQLite database, the Kanban view updates correctly, and new records added via the API appear as expected. However, the issue occurs only with a PostgreSQL database.
- I uses Docker Compose, with volumes configured for storing the PostgreSQL database data. I am not sure if this is related to the problem.
- It is worth noting that the new records are visible in other views, and they are assigned a system-generated ID and other expected attributes.

Thank you for your assistance!

**Comment by DarkPhoenix2704** [comment]
Just verified in latest Develop. Not reproducible.
