### ISSUE TITLE
NC_PUBLIC_URL not respected in subdirectory reverse proxy format

### ISSUE THREAD

**Issue by alfureu** [nocodb/nocodb#1033]
**Please enter the following details**

NocoDB used as docker : true 
NocoDB version : 0.84.8
Database used in NC_DB URL  : pg
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created : pg
OS on which NocoDB is running : CentOS 7.0
Node.js version if running as node : -
Database version : -

**Steps To Reproduce**
1. run docker container
2. define under environments NC_PUBLIC_URL=[sub.domain.tld/nocodb] and NC_BACKEND_URL=[http://IP:port]
3. try to define nocodb instance instead of subdomain format (e.g. nocodb.domain.tld) as a subdirectory (e.g. sub.domain.tld/nocodb) in nginx or Nginx Proxy Manager (NPM)
4. Whenever one types `sub.domain.tld/nocodb`. the NC_PUBLIC_URL is not respected and switches to `sub.domain.tld/dashboard`; also, the page is clearly available from `sub.domain.tld` as well, although it is defined in NPM as `sub.domain.tld/nocodb`

**Expected behavior**
NC_PUBLIC_URL should be respected and the address should be consequently `sub.domain.tld/nocodb/dashboard`

Also, please provide detailed documentation for main reverse proxy setups (caddy, nginx, Nginx Proxy Manager, traefik, etc).

**Comment by ericparland** [comment]
Same issue, seems like issue 428 was re-introduced again.

**Comment by bonacci-johannes** [comment]
Any update on this issue? Can one provide an instruction how to set enviorment variables when using reverse proxies?

**Comment by marcw** [comment]
I can confirm there are issues when using reverse proxy and subfolders. 

I got a working setup with these environment variables:

```.env
NC_DASHBOARD_URL=/nocodb/dashboard
NC_PUBLIC_URL=https://blabla.net/nocodb
NUXT_PUBLIC_NC_BACKEND_URL=https://blabla.net/nocodb
```

and this Caddy reverse proxy configuration bit:

```Caddyfile
# Contrary to handle_path, the handle directive does not strip prefix.
# We do not want the prefix to be stripped, so we use the handle directive.
handle /nocodb* {
  # The nocodb API server doesn't handle prefixes correctly
  uri /nocodb/api* strip_prefix /nocodb

  reverse_proxy http://nocodb:8080
}
```

**Comment by SternlyWindy** [comment]
Also interested in this. Running into the same issue using nginx.

**Comment by saurabhnanda** [comment]
@pranavxc Even I'm facing this issue. Do we know in which version was this re-introduced? I don't mind downgrading till the latest version contains a fix.

**Comment by pranavxc** [comment]
@saurabhnanda :  Can you share the version which you are using currently and are you defining `NC_PUBLIC_URL` environment ?

**Comment by saurabhnanda** [comment]
> @saurabhnanda : Can you share the version which you are using currently and are you defining `NC_PUBLIC_URL` environment variable?

@pranavxc I'm using the latest docker image `nocodb/nocodb:latest` which has the checksum `d0a41b9f5e5e`. 

I tried TWO setups and both of them didn't work out:

1. UI & API, both in the same subdir:

    ```
    # the docker-compose file for my project (nocodb is being used as part of a larger project)
    
    nocodb:
      image: "nocodb/nocodb:latest"
      networks:
        - internal
      environment:

        NC_DB: "REDACTED"
        NC_AUTH_JWT_SECRET: "REDACTED"
        NC_DASHBOARD_URL: /nocodb/dashboard
        NC_PUBLIC_URL: "http://${APP_DOMAIN}/nocodb"
        NUXT_PUBLIC_NC_BACKEND_URL: "http://${APP_DOMAIN}/nocodb"
    ```


    ```
    location /nocodb {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://nocodb:8080;
    }
    ```


2. UI in a different subdir and API in a different subdir
    ```
    # the docker-compose file for my project (nocodb is being used as part of a larger project)
    
    nocodb:
      image: "nocodb/nocodb:latest"
      networks:
        - internal
      environment:

        NC_DB: "REDACTED"
        NC_AUTH_JWT_SECRET: "REDACTED"
        NC_DASHBOARD_URL: /noco-ui
        NC_PUBLIC_URL: "http://${APP_DOMAIN}/noco-api"
        NUXT_PUBLIC_NC_BACKEND_URL: "http://${APP_DOMAIN}/noco-api"
    ```


    ```
    location /noco-ui {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://nocodb:8080;
    }

    location ~ ^/noco-api(/?)(.*) {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://nocodb:8080/$2;
    }
    ```

**Comment by pranavxc** [comment]
Use the following and try to access the dashboard path directly, for example: `http://your_domain/nocodb/dashboard` ( with your old config try `http://your_domain/nocodb/nocodb/dashboard`). If it works then it's related to redirect path related.

```
nocodb:
  image: "nocodb/nocodb:latest"
  networks:
    - internal
  environment:

    NC_DB: "REDACTED"
    NC_AUTH_JWT_SECRET: "REDACTED"
    NC_DASHBOARD_URL: /dashboard
    NC_PUBLIC_URL: "http://${APP_DOMAIN}/nocodb"
    NUXT_PUBLIC_NC_BACKEND_URL: "http://${APP_DOMAIN}/nocodb"
```

**Comment by pranavxc** [comment]
> @pranavxc I can confirm that subdomain based proxying works, but subdirectory based proxying doesn't

Thanks for confirming we will look into it.

**Comment by duoshaga** [comment]
> @pranavxc I can confirm that subdomain based proxying works, but subdirectory based proxying doesn't

This configuration looks to work.
`
      NC_DASHBOARD_URL: "/nocodb/ui"
      NC_PUBLIC_URL: "https://${APP_DOMAIN}/nocodb"
      NUXT_PUBLIC_NC_BACKEND_URL: "https://${APP_DOMAIN}/nocodb"
`
`
    location ~ /nocodb\/ui {
        proxy_http_version   1.1;
        proxy_pass http://ip:port;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
`
`
    location ~ /nocodb\/(.*) {
        proxy_http_version   1.1;
        proxy_pass http://ip:port/$1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
`
But there is an error in the operation table.
![image](https://github.com/nocodb/nocodb/assets/39816460/116a2e73-42e8-4583-955c-ef4cc543b440)

**Comment by RepComm** [comment]
The reply above worked for me with latest nginx and nocodb from podman containers. Thank you so much [duoshaga](https://github.com/duoshaga)!

**Comment by cwhy** [comment]
An easier setup also works for me:
```
 NC_DASHBOARD_URL: "/nocodb/dashboard"
```

```
    location /nocodb/dashboard {
        proxy_http_version   1.1;
        proxy_pass http://ip:port;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location /nocodb/ {
        proxy_http_version   1.1;
        proxy_pass http://ip:port/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
```

**Comment by lolgopher** [comment]
There are several problems with the subdirectory based proxying method, as described in issue #6147.

I want to fix it because I have to use it as a subdirectory based proxying. in PR #6157

**Comment by dstala** [comment]
fixed here https://github.com/nocodb/nocodb/pull/6157
if anything more required, please reopen this ticket

**Comment by beremour** [comment]
thank you!

**Comment by garylavayou** [comment]
Come from version `2026.05.1`, the problem still exists. Main issues are:

- static resources URLs are not affected by environment variables;
- `NC_DASHBOARD_URL` will not be added to the URL accessed from browser;

---

NocoDB is configured with the following environment variables:

```shel
NC_SITE_URL="https://nocodb.example.com/nocodb"
NC_DASHBOARD_URL='/nocodb/dashboard'
NUXT_PUBLIC_NC_BACKEND_URL='http://localhost:8080/nocodb'
```

Following the nginx confiuration provided by @cwhy and [^pr6157], I have configured the reverse proxying rules with traefik (with docker labels):

```yaml
services:
  nocodb:
    labels:
      - "traefik.http.routers.nocodb.rule=Host(`nocodb.example.com`) && PathPrefix(`/nocodb/dashboard`)"
      - "traefik.http.routers.nocodb.tls.domains[0].main=nocodb.example.com"
      - "traefik.http.routers.nocodb.entrypoints=https"
      - "traefik.http.routers.nocodb2.rule=Host(`nocodb.example.com`) && PathPrefix(`/nocodb/`)"
      - "traefik.http.routers.nocodb2.tls.domains[0].main=nocodb.example.com"
      # fallback rule for loading resources that does not have /nocodb prefix
      - "traefik.http.routers.nocodb2.entrypoints=https"
      - "traefik.http.middlewares.strip-nocodb-prefix.stripprefix.prefixes=/nocodb"
      - "traefik.http.routers.nocodb2.middlewares=strip-nocodb-prefix"
```

It is expected that the service frontend is accessed from `https://nocodb.example.com/nocodb`.
Actually, the following behavior is observed via Chrome's devtool:

1. ✅`/nocodb/dashboard` is redirected to `/nocodb/dashboard/`, which loading the dashboard app's main HTML page.
1. ❌Static resources in the HTML page is accessed via `/_nuxt/` prefix, instead of `/nocodb/_nuxt/`.
   This is because all resource in the `/nocodb/dashboard/` is given as abosolute path instead of path related to `/nocodb/dashboard/` (actually, it should related to `/nocodb/dashboard`), like:

   ```html
   <link rel="prefetch" as="style" crossorigin href="/_nuxt/LockView.DhFZqGXn.css">
   ```

   As all static resource cannot be loaded, the HTML page cannot be rendered.

To allow static resource to be loaded, I have to add another rule to pass those requests that does not match the routing rule directly to the backend service (However, this rule does not conform to the requirement of adding common URL prefix `/nocodb`).

The Following issues still occure:

1. ✅The request of `/nocodb/socket.io/` is as expected.
1. ❌`/404` should be `/nocodb/404`.
1. ❌Backend API URL is not affected by URL configurations, like `/api/v1/auth/user/me`, which should be requested as `/nocodb/api/v1/auth/user/me`.
1. ❌The URL prefix `/nocodb/dashboard/` is parsed as workspace id for API request `/api/v1/auth/user/me?workspace_id=nocodb` or `/api/v1/auth/user/me?base_id=dashboard&workspace_id=nocodb`, as the workspace and base ID SHOULD HAVE presented in the end of the URL.
1. ❌`/dashboard` might be appended to `/api/v1/db/meta/projects/dashboard` as project ID, which cannot be found.
1. ❌`/nocodb/dashboard` might be appended `/api/v2/internal/nocodb/dashboard` as base and project ID, which cannot be found.

[^pr6157]: [Fixed: Reverse proxy by nocodb](https://github.com/nocodb/nocodb/pull/6157)

**Comment by garylavayou** [comment]
NocoDB is configured with the following environment variables:

```shel
NC_SITE_URL="https://nocodb.example.com"
NC_DASHBOARD_URL='/nocodb/dashboard'
NUXT_PUBLIC_NC_BACKEND_URL='http://localhost:8080'
```

With the onfiguration of traefik labels:

```yaml
services:
  nocodb:
    labels:
      # access from https://nocodb.example.com
      - "traefik.http.routers.nocodb3.rule=Host(`nocodb.example.com`)"
      - "traefik.http.routers.nocodb3.tls.domains[0].main=nocodb.example.com"
      - "traefik.http.routers.nocodb3.entrypoints=https"
```

The frontend is accessed from `https://nocodb.example.com`, URL in browser is showing as `https://nocodb.example.com/<workspace-id>/<project-id>` or `https://nocodb.example.com/<workspace-id>`.
So `NC_DASHBOARD_URL` does not take effect!

Related issues:

- https://github.com/nocodb/nocodb/issues/11882
