### ISSUE TITLE
🐛 Bug: File Attachments Disappeared | Backblaze B2 Integration

### ISSUE THREAD

**Issue by candideu** [nocodb/nocodb#11995]
### Please confirm that the bug report does ***not*** already exist

- [x] I confirm there is no existing issue for this bug.

### Steps to reproduce

Hello! I've been self-hosting nocodb on Railway since 2022, and was using it to upload audio files. I've only recently noticed, after upgrading to [0.264.0](https://github.com/nocodb/nocodb/releases/tag/0.264.0), that my file attachments have disappeared and aren't being displayed in Nocodb.

They are there on the Backblaze side of things, but completely absent in NocoDB, despite being visible in past versions:

<img width="1006" height="388" alt="Image" src="https://github.com/user-attachments/assets/0f373bc1-251d-41fb-89a6-f7389eab1cc5" />

When I peak inside the revision history to find the URL of the file I uploaded back in 2022, I see something like this:

```
mp3-file : null [{"url":"https://bucket-name.s3.us-west-002.backblazeb2.com/nc/name_of_base_goya/db/uploads/nc_goya__name%20of%20_table/mp3-file_JXachw_audio.mp3","title":"audio.mp3","mimetype":"audio/mpeg","size":119169}]
```

When I try to access the link (in the case of my example: `https://bucket-name.s3.us-west-002.backblazeb2.com/nc/name_of_base_goya/db/uploads/nc_goya__name%20of%20_table/mp3-file_JXachw_audio.mp3`), I'm able to download the file from Backblaze.

One of my Table views is embedded on a website, and the attachment field only shows "Source data is read-only" (despite file downloads being possible in the past, and that being the point of my public base):

<img width="974" height="573" alt="Image" src="https://github.com/user-attachments/assets/396475d0-0cb1-429c-99aa-12e2611d0e7e" />

### Desired Behavior

File attachments previously uploaded via NocoDB and already in Backblaze should be accessed and played back inside NocoDB

### Project Details

Hosted on railway.com

NocoDB version: [0.264.0](https://github.com/nocodb/nocodb/releases/tag/0.264.0)
Node: **v22.17.1**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.264.0**

**Comment by o1lab** [comment]
There was an attachment related fix in latest release. See if the issue still exists.

**Comment by candideu** [comment]
@o1lab I've upgraded, and the issue persists, unfortunately.

**Comment by fendy3002** [comment]
hello @candideu , we have made another fix. Can you please check whether this build:

```
docker run -d -p 8888:8080 nocodb/nocodb-timely:0.264.1-pr-12010-20250731-0635
```

fixes it?

**Comment by pranavxc** [comment]
Fixed here #12010

**Comment by candideu** [comment]
I've upgraded to 0.264.2, and I still don't see my attachments... Please re-open this issue.

<img width="955" height="995" alt="Image" src="https://github.com/user-attachments/assets/853bec82-d071-46bf-a348-fdd03a98cee1" />

Node: **v22.17.1**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.264.2**

**Comment by candideu** [comment]
Quick Update: I've just upgraded to 0.264.3, and I'm still not seeing my attachments.

**Comment by fendy3002** [comment]
hi @candideu , we have tried some scenario for this without success. We need more information on the scenario.

* from what version do you upgrade before 0.264.0?
* can you check on the row values for the Attachment column? If using UI, you can do it using [network tab](https://developer.chrome.com/docs/devtools/network). Filter for `Fetch / XHR` and search with model id (on the url that start with `m`). Then check for preview / response.

<img width="1264" height="207" alt="Image" src="https://github.com/user-attachments/assets/46a669c0-d02e-4500-98b2-4375e6fa9c0d" />

<img width="1849" height="208" alt="Image" src="https://github.com/user-attachments/assets/1ee16f6f-80a9-47d5-8433-9d673a163568" />

* any operation that you do before having the attachment disappear?
* how many tables / rows are affected?

**Comment by pranavxc** [comment]
Hi @candideu, if possible, it’ll be easier to discuss this over a call. You can ping me in our Discord channel – https://discord.com/invite/5RgZmkW (my ID: pranavxc)

**Comment by fendy3002** [comment]
hello @candideu , Pranav has successfully identified the issue, we're working on the fix here:

```
docker run -d -p 8888:8080 nocodb/nocodb-timely:0.264.2-pr-12038-20250805-0730
```

if you'd like it can you check whether this build fix your issue?

**Comment by candideu** [comment]
> from what version do you upgrade before 0.264.0?

@fendy3002 : I document the version numbers I've upgraded to since the first deployment here: https://github.com/Digitized-Diasporic-Memory/nocodb-database-deploy/commits/main/

> can you check on the row values for the Attachment column?

Here's what I got:

<img width="1355" height="413" alt="Image" src="https://github.com/user-attachments/assets/9cbd5bdb-2855-4bd1-9f59-d892984f0e87" />

> any operation that you do before having the attachment disappear?

Not really. Haven't really done much to the base in the past few years besides upgrading the deployment.

> how many tables / rows are affected?

The entire base is affected.

**Comment by candideu** [comment]
> Pranav has successfully identified the issue, we're working on the fix here: `docker run -d -p 8888:8080 nocodb/nocodb-timely:0.264.2-pr-12038-20250805-0730` if you'd like it can you check whether this build fix your issue?

Just tried it, and it works!! 🥳🥳🥳

<img width="947" height="526" alt="Image" src="https://github.com/user-attachments/assets/27cbc039-e96a-479c-90cf-3ba9a0916db3" />

<img width="753" height="541" alt="Image" src="https://github.com/user-attachments/assets/f3b9cf3d-3667-4f2c-b85e-808d5040569a" />

Please let me know once the changes are part of the latest docker image, so that I can go back to that image. Thank you so much!!

**Comment by pranavxc** [comment]
@candideu: Thank you so much for verifying 🙏 We truly appreciate it. We've just rolled out a bug fix release – https://github.com/nocodb/nocodb/releases/tag/0.264.4.
