### ISSUE TITLE
[Feature] Use rollup in formula

### ISSUE THREAD

**Issue by PiotrKrzyzek** [nocodb/nocodb#1331]
## Recommending Features

**Need for this feature**
Allowing the results of a roll-up to be used in a formula will allow us to do more pivot-like and spreadsheet like calculations. For example:

Table A: Courses
Table B: Students

Course has a roll-up column of Student that is in said course giving us a total student count. Then, I could have column for max-seat-count ... say 20 seats available. And thus, I could then have a formula column which would do, which currently isn't possible: MaxSeatCount - RollUpCountOfStudentsInThisCourse = Seats Left

There are a lot of other possibilities, though currently there's just no way to get the results of a rollup to be used in calculations somewhere which has a lot of uses ranging from P&L statements, to inventory tracking, weather math fun and more. :)

**Comment by robrecord** [comment]
Yes please, and also use Lookup result in formula!

**Comment by o1lab** [comment]
Soon, stay tuned.

**Comment by dapeduu** [comment]
Any idea on when will it be available?

**Comment by occamssafetyrazor** [comment]
It would be great to have this feature. It's the only thing preventing our migration from airtable.
#1844 seems to be the root cause where @wingkwong points out:
> As virtual columns don't have column_name, it results in querying null columns.

**Comment by acidg** [comment]
Would also love to see this! With this feature implemented, I can finally switch from bloated Excel to awesome NocoDB! 🚀

**Comment by geofflambeth** [comment]
I see this issue has been inactive for a while, but just wanted to add to the list of supporters. This would be a spectacular feature to see implemented!

**Comment by sakam0to** [comment]
I can't wait to see it implemented. And yes, I am experiencing migration issues due to the lack of such feature.

**Comment by o1lab** [comment]
Available in the latest release. Can be closed.

**Comment by o1lab** [comment]
Available in the latest release. Can be closed.

**Comment by uebenes** [comment]
In the current release (0.109.4), this features is not in! Does this feature really ever was implemented?

**Comment by calvinlang** [comment]
Yes this would be huge! Especially for accounting work!

**Comment by francowxu** [comment]
I just tried a formula equals to a Rollup field, but still failed.  I'm using the cloud environment. https://app.nocodb.com/
![image](https://github.com/nocodb/nocodb/assets/6725251/879536c3-f9b3-41bb-b2ad-9e317114146e)
![image](https://github.com/nocodb/nocodb/assets/6725251/43512479-6425-4c1e-9c68-71f005464796)
![image](https://github.com/nocodb/nocodb/assets/6725251/a8e88998-a064-4a4b-aa16-176a5c9ec9b4)

**Comment by wingkwong** [comment]
resolved in above PR

**Comment by jeffhaskin** [comment]
Please reopen this issue, It's still not functional in the current version, and it's a major use case for rollup fields in general.

**Comment by dstala** [comment]
@jeffhaskin can you elaborate on your issue faced with rollup field usage in formula? I just tried a simple use in formula (direct reference), it works. 
![Screenshot 2024-08-10 at 5 32 17 AM](https://github.com/user-attachments/assets/56aa6204-1720-4bcb-bff7-88e77296426c)

**Comment by jeffhaskin** [comment]
Table: Task
Table: Sessions (A session of working on the task

Fields in Sessions Table:
1. Title
2. Linked Task
3. Start Datetime
4. Stop Datetime
5. Duration (formula Field)

Tasks Table relevant Field:
Rollup of the Duration field from all linked session records.

In this instance, "Duration" doesn't even show up in the list of fields in the rollup menu.

<img width="858" alt="image" src="https://github.com/user-attachments/assets/a1e9d322-75db-4430-8e96-1fdea3ef234b">


<img width="969" alt="image" src="https://github.com/user-attachments/assets/90d22194-de66-4b12-a742-bde6ce1f4578">

**Comment by RossoSwap** [comment]
Any news on this? And on the ability to use filters in rollup?

**Comment by dstala** [comment]
Support for formula field when creating Rollup field is provided now. If you face any issue, do let us know.
