### ISSUE TITLE
[Feature]  Undo - Recover deleted row

### ISSUE THREAD

**Issue by Tupax** [nocodb/nocodb#1425]
We need a place to **restore deleted rows** of a table.

The problem is when we mistakenly delete a row. Or if we want to rollback a deleted row. There's no way to recover it back.

A good place to solve this problem, is the **audit section**.

![Screenshot 2022-03-09 at 17-13-34 NocoDB](https://user-images.githubusercontent.com/21961972/157527481-698a9cbe-cfb4-4823-a650-c82315a2b992.png)

**Comment by lublak** [comment]
It would be interesting not only when deleting but also when editing when you have changed values.

**Comment by nalafod** [comment]
This would be a nice addition to when someone has removed or changed something and we only realize it few hours later

**Comment by sudoexec** [comment]
Really need this.
Althought "prevent undo while editing" is fixed in  https://github.com/nocodb/nocodb/pull/5989, sometimes undo will be misused as described in https://github.com/nocodb/nocodb/discussions/5979 when there's a network erros.

**Comment by llama0815** [comment]
I second this feature. 

Instead of unlinking a child list, I deleted it. That button shouldn't be there. Very confusing.

**Comment by nocodbenjoyer** [comment]
Been over 1.5 years now, still not there. The undelete feature is paramount.

**Comment by dstala** [comment]
@nocodbenjoyer Undo feature is now part of the NocoDB. You noticed any specific issue/behaviour that needs correction?

**Comment by c0dehammer** [comment]
Hi, Do we have an undo history ?

**Comment by dstala** [comment]
@garathds not linked with audit history, but many of the operations carried out within NocoDB have undo support.
