### ISSUE TITLE
Cannot click tables on mobile

### ISSUE THREAD

**Issue by andriesteddy** [nocodb/nocodb#6234]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

On android, from the home screen open a project.
In the project try to view a table by clicking its name in the left hand menu. It does seem to select the table because the name of the table lights up, however the table contents is not shown. 

This does work fine on the desktop version.

### Desired Behavior

Whenever I click the table on a mobile platform i like to be able to view and edit its contents.

### Project Details

Node: **v16.16.0**
Arch: **x64**
Platform: **win32**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.111.0**

**Comment by dstala** [comment]
good number of issues related to mobile responsive view are resolved in our latest release. reopen this issue if you face any new issue with mobile responsiveness.

**Comment by andriesteddy** [comment]
Can this issue be re-opened? This issue still persists (using chrome).
