### ISSUE TITLE
Cannot upload attachment in shared form view

### ISSUE THREAD

**Issue by savvidis** [nocodb/nocodb#687]
NocoDB used as docker : false
NocoDB version : 0.11.46
Database used in NC_DB URL  : 
Project was created  by clicking :  New Project by connecting to external database
Database on which spreadsheet is created : pg 
OS on which NocoDB is running : 
Node.js version if running as node : 
Database version : 

1. Go to a Form view 
2. Share View 
2. In the shared view click to upload an attachment 
3. See error

**Expected behavior**
To upload the file as it does in the Table view and in the Form view in edit mode

**Screenshots**
![image](https://user-images.githubusercontent.com/2984660/138362407-4ddf203d-eda4-463e-9120-4119f4c20baa.png)
![image](https://user-images.githubusercontent.com/2984660/138362533-f447c800-ccff-4d2b-bd86-d67c0b0e18e5.png)

Join our discord : https://discord.gg/5RgZmkW for realtime help.

Node: **v14.17.6**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **sqlite3**
PackageVersion: **0.11.46**

**Comment by o1lab** [comment]
Will be available in > 0.80

**Comment by pranavxc** [comment]
Fixed in `0.81.0`

**Comment by vmazmaz** [comment]
The problem is still there for me. Attachment upload works fine in edit mode but generates an error 401 in public view mode.

Node: **v20.15.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.255.1**
