### ISSUE TITLE
URL columns should accept file:// protocol

### ISSUE THREAD

**Issue by eevleevs** [nocodb/nocodb#746]
Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **mssql**
ProjectOnRootDB: **true**
RootDB: **mssql**
PackageVersion: **0.81.1**

**Comment by RalphBln** [comment]
I second this and suggest that the request be extended to include *all* valid protocols.

**Comment by jpbourgeon** [comment]
I too would need this feature. In an internal dashboard setup, it would be particularly useful to allow direct linking to a client's folder in the filesystem.

**Comment by jpbourgeon** [comment]
Here is the list of URI schemes <https://en.wikipedia.org/wiki/List_of_URI_schemes>
It's very long
It may be more convenient and more secure to let the admin specify in an environment variable a custom coma separated list of allowed URI schemes , defaulting to https only.
This would let the admin take into account project specific (external app specific non official URL scheme) constraints without sacrificing security concerns.
eg. `ALLOWED_URI_SCHEMES:https,file,sftp`

**Comment by frankMagoba** [comment]
@o1lab  Is this issue still up?

**Comment by dstala** [comment]
https://github.com/nocodb/nocodb/issues/469

**Comment by thewindsofwinter** [comment]
@dstala does this remain or is the issue already resolved via #469 ? would be happy to contribute if functionality is still needed

**Comment by jpbourgeon** [comment]
@thewindsofwinter 
The URL field now accepts various schemes: I tested with `ftp://` succesfully.

However It's still not working with the `file://` scheme 
When this scheme is used, the field is not converted into a clickable link and behaves likes a basic text string.

**Comment by xximj** [comment]
> @thewindsofwinter 
> The URL field now accepts various schemes: I tested with `ftp://` succesfully.
> 
> However It's still not working with the `file://` scheme 
> When this scheme is used, the field is not converted into a clickable link and behaves likes a basic text string.
> 

file:// links are blocked from http:// or https:// pages in all major browsers for security reasons.

There are some workarounds and extensions if you still need that feature.

**Comment by Balot0x00** [comment]
What about support for other protocols like chrome:// weixin://?
I've tested it with things like chrome:// and edge:// but both are forced to convert to https://

<img width="262" height="52" alt="Image" src="https://github.com/user-attachments/assets/032b7ad7-8653-47d4-901c-b519c55b0fda" />
