### ISSUE TITLE
🐛 Bug: Form iFrames broken (403 Not Allowed)

### ISSUE THREAD

**Issue by 3699n** [nocodb/nocodb#7828]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Create a form, make it public, copy the iframe code, and try to embed it in a website.

![image](https://github.com/nocodb/nocodb/assets/7414843/0703f371-02ec-4ffa-9c63-02559ef1711d)

While the form is accessible in any regular browser, it cannot be access as an iframe.

![image](https://github.com/nocodb/nocodb/assets/7414843/58e38c7e-a6f8-4012-8193-def023f5d875)

### Desired Behavior

The form should function as an iframe as it did in previous version.

### Project Details

´´´
Node: **v18.5.0**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.204.4**
´´´

**Comment by dstala** [comment]
```
entry.UBRgQws3.js:280 [nuxt] error caught during app initialization Error: Not allowed
    at GC (entry.UBRgQws3.js:1:108147)
    at qg (entry.UBRgQws3.js:1:110575)
    at Soe (entry.UBRgQws3.js:9:1976)
    at entry.UBRgQws3.js:274:13947
    at r (entry.UBRgQws3.js:1:105711)
    at Object.runWithContext (entry.UBRgQws3.js:1:43087)
    at Zte (entry.UBRgQws3.js:1:105741)
    at entry.UBRgQws3.js:1:103979
    at mF.run (entry.UBRgQws3.js:1:4464)
    at Object.runWithContext (entry.UBRgQws3.js:1:103971)
    at entry.UBRgQws3.js:274:13928
```

**Comment by jakob1379** [comment]
same for me with the latest docker image nocodb/nocodb:0.204.4 - the sample code with my own url gives a 403 image as above, but using the url directly, not embedded, works.

**Comment by dstala** [comment]
fixed. should be available in next release.

**Comment by feige-2011** [comment]
Hello, I have encountered the same problem. The latest code for my git clone did not solve this problem. I would like to ask which release version this will be resolved in

**Comment by feige-2011** [comment]
> same for me with the latest docker image nocodb/nocodb:0.204.4 - the sample code with my own url gives a 403 image as above, but using the url directly, not embedded, works.


Hello friend, have you solved this problem?

**Comment by Shihira** [comment]
using 0.258.10, the same issue still exists.

**Comment by guiz01** [comment]
Alguma solução para este problema?
